"""Write COVERAGE-STATUS.md: every MMBasic name, its status, its category.

    python3 fcc/mkstatus.py > COVERAGE-STATUS.md

Names and status come from statuslist.py (AllCommands.h + mmb2c's own
dispatch); the category for a gap comes from catmap.py, which is hand
kept because it is a judgement. Anything unclassified is reported as
such rather than silently dropped - that is how a new MMBasic release
shows up here.
"""
import subprocess
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import catmap

here = os.path.dirname(os.path.abspath(__file__))
out = subprocess.check_output(
    [sys.executable, os.path.join(here, "statuslist.py")]).decode()

rows = []
for line in out.splitlines():
    p = line.split("\t")
    if len(p) == 3:
        rows.append(p)

cmds_yes = [r[1] for r in rows if r[0] == "cmd" and r[2] == "yes"]
fns_yes = [r[1] for r in rows if r[0] == "fn" and r[2] == "yes"]
miss = [(r[0], r[1]) for r in rows if r[2] == "no"]

# de-duplicate: AllCommands.h has a few repeated rows (Camera, Backlight,
# Draw3D each appear twice, CtrlVal as both a command and a function)
seen = set()
missu = []
for kind, nm in miss:
    if (kind, nm) in seen:
        continue
    seen.add((kind, nm))
    missu.append((kind, nm))

bycat = {}
unknown = []
for kind, nm in missu:
    c = catmap.CAT.get(nm)
    if c is None:
        unknown.append((kind, nm))
    else:
        bycat.setdefault(c, []).append((kind, nm))

fn = bycat.pop("FN", [])
real = sum(len(v) for v in bycat.values())

W = []
W.append("# MMBasic coverage: every command and function, "
         "with status\n")
W.append("Generated by `fcc/mkstatus.py` on "
         + __import__("datetime").date.today().isoformat()
         + ". **Neither half "
         "is hand written**: the names come from MMBasic's own\n"
         "`AllCommands.h` and the status from `mmb2c.py`'s dispatch and "
         "`BUILTINS` table, read the same way\n"
         "`mmbedit/genkw.py` reads them - so this cannot flatter us. Only "
         "the CATEGORY of a gap is a judgement,\n"
         "and it lives in `fcc/catmap.py`.\n")

W.append("## The numbers\n")
W.append("| | in MMBasic | translated | not translated |")
W.append("|---|---|---|---|")
W.append("| commands | %d | **%d** | %d |"
         % (len([r for r in rows if r[0] == "cmd"]), len(cmds_yes),
            len([r for r in rows if r[0] == "cmd" and r[2] == "no"])))
W.append("| functions | %d | **%d** | %d |"
         % (len([r for r in rows if r[0] == "fn"]), len(fns_yes),
            len([r for r in rows if r[0] == "fn" and r[2] == "no"])))
W.append("| total | %d | **%d** | %d |\n"
         % (len(rows), len(cmds_yes) + len(fns_yes), len(miss)))

W.append("The %d not-translated rows include names AllCommands.h lists TWICE - Camera, Backlight and\nDraw3D each appear twice, CtrlVal as both a command and a function - so there are **%d distinct\nnames**. Of those, **%d are false negatives** (the thing works and the scanner cannot see it),\nleaving **%d real gaps**, of which %d are in categories 4 and 5 and are not intended to close.\n"
         % (len(miss), len(missu), len(fn), real,
            len(bycat.get(4, [])) + len(bycat.get(5, []))))

W.append("## What this count cannot tell you\n")
W.append("**A name counted as translated may be only PARTLY translated, "
         "and this list cannot see the\ndifference.** The unit here is a "
         "row in AllCommands.h, and several rows are whole families:\n")
W.append("* `Math` is one row and **67 members** - the MATH section at "
         "the end counts them honestly.")
W.append("* `GUI` is one row and only `GUI BITMAP` is translated.")
W.append("* `Load` is one row covering `IMAGE`, `BMP`, `JPG` and `PNG` "
         "here, and a dozen forms in MMBasic.")
W.append("* `Option`, `MM.INFO` and `Print` each take a list of "
         "sub-keywords, some in and some not.\n")
W.append("So read the numbers as \"names the translator dispatches\", "
         "which is what they are, and not as a\npercentage of MMBasic. "
         "The honest per-feature figure is lower, and the only way to get "
         "it is the\nway the MATH section does it: read the reference's "
         "own sub-tables.\n")
W.append("**And it can understate, in one specific place.** MMBasic ran "
         "out of room in its function table, so\nit COMMENTED NAMES OUT "
         "of it and made the tokeniser rewrite them into a shared entry "
         "that takes a\nselector letter: `Hex$(`, `Oct$(` and `Bin$(` all "
         "become `base$(`; `Left$(`, `Right$(`, `UCase$(` and\n"
         "`LCase$(` become `SChange$(`; `Max(` and `Min(` become "
         "`TopBottom(`; and the flat `MM.*` reads become\n`~(`. Those nine "
         "functions are therefore ABSENT from AllCommands.h and so absent "
         "from every list\nbelow - and all nine are translated, as are 14 "
         "of the `MM.*` reads. The four wrapper spellings are\nin category "
         "4: we translate source text, not MMBasic's tokenised form, and "
         "`Functions.c` keeps all\nfour inside its "
         "\"excluded from the documentation\" block.\n")

W.append("## The five categories\n")
for k in (1, 2, 3, 4, 5):
    W.append("%d. **%s** - %d" % (k, catmap.NAMES[k], len(bycat.get(k, []))))
W.append("")

if fn:
    W.append("## False negatives: implemented, invisible to the scan\n")
    W.append("These are dispatched somewhere the scan does not look - the "
             "lexer, the expression grammar, or a\ntwo-word branch. They "
             "are listed so the count above is honest, and because this "
             "class has\nmisled us before (`DefineFont` and `BLIT MEMORY` "
             "both read as missing while they worked).\n")
    W.append("`" + "`, `".join(nm for _, nm in fn) + "`\n")

for k in (1, 2, 3, 4, 5):
    lst = bycat.get(k, [])
    if not lst:
        continue
    W.append("## Category %d - %s (%d)\n" % (k, catmap.NAMES[k], len(lst)))
    c = [nm for kind, nm in lst if kind == "cmd"]
    f = [nm for kind, nm in lst if kind == "fn"]
    if c:
        W.append("**Commands:** `" + "`, `".join(sorted(c)) + "`\n")
    if f:
        W.append("**Functions:** `" + "`, `".join(sorted(f)) + "`\n")
    note = getattr(catmap, "NOTES", {}).get(k)
    if note:
        W.append(note + "\n")

if unknown:
    W.append("## UNCLASSIFIED - add these to fcc/catmap.py (%d)\n"
             % len(unknown))
    W.append("`" + "`, `".join(nm for _, nm in unknown) + "`\n")

# ... and the other direction, which nothing used to check: an entry in
# catmap for a name that now TRANSLATES.  It changes no count - the
# categories only classify gaps - but it is a decision recorded about
# something that has since been done, and catmap's own stated policy is
# that such an entry is dead weight.  WS2812 and Bitstream sat there for
# a day; this is what would have said so.
translated = set(cmds_yes) | set(fns_yes)
dead = sorted(nm for nm in catmap.CAT if nm in translated)
if dead:
    W.append("## Dead entries in fcc/catmap.py - these names now "
             "translate (%d)\n" % len(dead))
    W.append("`" + "`, `".join(dead) + "`\n")

W.append("## Translated: the %d commands\n" % len(cmds_yes))
W.append("`" + "`, `".join(sorted(cmds_yes)) + "`\n")
W.append("## Translated: the %d functions\n" % len(fns_yes))
W.append("`" + "`, `".join(sorted(fns_yes)) + "`\n")

print("\n".join(W))

# The MATH section is the honest per-member count this document points
# at as its own antidote to name-level flattery, and it lives in its own
# generator.  It is appended HERE because the command in the docstring
# above is the one people run, and running it without this line quietly
# produced a COVERAGE-STATUS.md with the whole section missing.
print()
sys.stdout.flush()
subprocess.check_call([sys.executable,
                       os.path.join(os.path.dirname(
                           os.path.abspath(__file__)), "mathstatus.py")])
