/* ------------------------------------------------------------------
 * mmb_runtime.h  -  support runtime for C code generated by mmb2c.py
 *
 * Strings follow the MMBasic internal convention:
 *
 *      s[0]        = length  (0..255, unsigned)
 *      s[1..len]   = the characters (may include CHR$(0))
 *      s[len+1]    = a NUL, maintained by the runtime purely so that a
 *                    string can be handed to C library calls cheaply.
 *                    It is NOT part of the string and is never counted.
 *
 * A string variable is therefore  char x[MM_STRSZ];  and is passed
 * around as a plain char* .  Nothing is ever malloc'd.
 * ------------------------------------------------------------------ */
#ifndef MMB_RUNTIME_H
#define MMB_RUNTIME_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef double  MMFLOAT;
typedef int64_t MMINTEGER;

/* Maximum characters in a string. MMBasic's own limit is 255. */
#ifndef MM_STRLEN
#define MM_STRLEN 255
#endif
/* storage = length byte + data + trailing NUL */
#define MM_STRSZ (MM_STRLEN + 2)

/* MAXERRMSG in the firmware (configuration.h:382): MM.ERRMSG$ is
 * truncated to this, so a program comparing the text sees the same
 * cut-off here. */
#define MM_ERRMSG 64

/* Number of scratch buffers used for string expression temporaries.
 * Each costs MM_STRSZ bytes of static RAM.  They are handed out as a
 * stack: every generated function takes a mark on entry and every
 * statement releases back to it, so the high-water mark is set by the
 * most string-heavy single expression - INCLUDING the functions it
 * calls, whose own peaks stack on the caller's.  16 lasted until
 * PETSCII Robots' config reader: LCase$(Field$(Field$(s$,...,
 * Chr$(34)),..., Chr$(34))) inside a function called from a
 * string-using statement.  The interpreter has no such cap; 32 is
 * 8K of bss, which the board's bcrun can afford. */
#ifndef MM_TMPN
#define MM_TMPN 32
#endif

/* Format used when PRINTing a float. */
#ifndef MM_FLOATFMT
#define MM_FLOATFMT "%.10g"
#endif

/* ---- scratch buffers ---------------------------------------------- */
char    *mm_tmp(void);              /* push a scratch buffer, set to "" */
unsigned mm_mark(void);             /* current top of the scratch stack */
void     mm_release(unsigned mark); /* pop back down to 'mark'          */

/* ---- the heap ------------------------------------------------------
 *
 * One block for every array and string in the program.
 *
 * mmb2c puts them in a single struct and calls mm_heap once, so the
 * whole of a program's bulk data is one allocation - one free at exit,
 * no fragmentation, and sizeof does the sizing.  Scalars stay in the
 * process image, where they are 3.7x faster to reach (SRAM 44MB/s,
 * PSRAM 12MB/s measured).
 *
 * LOCAL arrays and strings get the same treatment per routine, one
 * block per invocation, which is what makes recursion correct: each
 * call has its own and gives it back on every path out.  They are
 * separate names from mm_heap because their lifetimes are: mm_lheap is
 * called on every invocation of a routine, so it must never be more
 * expensive than an allocation, where mm_heap is called once and can
 * afford to ask the kernel.
 *
 * Under bcrun both come from the VM heap, which is itself PSRAM.
 * Everywhere else they are malloc, so the generated C stays portable
 * and the host gates keep working.  Zeroed either way. */
void *mm_heap(unsigned long n);
void *mm_lheap(unsigned long n);
void  mm_lfree(void *p);

/* Park a value and return its address: how a by-reference argument is
 * built from an expression on a compiler with no compound literals
 * (mmb2c --fcc).  A stack wound back by the same mark/release as the
 * string temporaries, so the value lives exactly as long as the call
 * statement it was built for - however long the callee runs.  At most
 * MM_BYREFN can be live at once (call nesting x by-ref args).        */
/*
 * 256 of them, because this is what bounds RECURSION.
 *
 * The slot cannot be released until the call returns - the callee is
 * holding its address - so a recursive routine holds one per argument
 * per level, all the way down.  At 16 a routine as ordinary as
 * "go n + 1" died at fifteen levels with "Expression too complex",
 * which is no depth at all: a balanced tree walk over a million nodes
 * is twenty, quicksort on ten thousand items is forty.
 *
 * A slot is a union of MMFLOAT and MMINTEGER, so 256 costs 2K of the
 * VM region - shared with bss, the stack and (off-board) the heap.
 * That buys 256 levels of a one-expression call and 128 of a two,
 * which covers what recursion is actually used for.
 *
 * The principled fix is to put these in the routine's own LOCAL frame,
 * which nests with the calls and falls through to malloc when it runs
 * out - no wall at all.  That is an emitter change in both
 * translators; this is a constant.
 */
#ifndef MM_BYREFN
#define MM_BYREFN 256
#endif
MMFLOAT   *mm_byref_f(MMFLOAT v);
MMINTEGER *mm_byref_i(MMINTEGER v);

/* ---- core string ops ---------------------------------------------- */
#define mm_slen(s)  ((int)(unsigned char)(s)[0])
#define mm_cstr(s)  ((const char *)((s) + 1))   /* NUL-terminated view  */

void   mm_sset (char *d, const char *s);            /* d = s           */
void   mm_ssetc(char *d, const char *cstr);         /* from C string   */
void   mm_ssetn(char *d, const char *raw, int n);   /* from raw bytes  */
void   mm_ssetm(char *d, int cap, const char *s);   /* TYPE member: bounded,
                                                       NUL only if room */
char  *mm_scat (const char *a, const char *b);      /* a + b  -> temp  */
int    mm_scmp (const char *a, const char *b);      /* <0, 0, >0       */
char  *mm_scopy(const char *s);                     /* s -> temp       */

/* ---- console output ------------------------------------------------ */
void mm_putc  (int c);
void mm_pr_s  (const char *s);      /* PRINT a string                  */
void mm_pr_i  (MMINTEGER v);        /* PRINT an integer                */
void mm_pr_f  (MMFLOAT v);          /* PRINT a float                   */
void mm_pr_nl (void);               /* end of PRINT line               */
/* The LAST item of a PRINT that ends in ; or , - print it and flush,
 * so a partial line reaches the screen instead of waiting in stdio's
 * buffer for the next newline.  Print-and-flush rather than a separate
 * flush call: one extra statement in main is enough to tip a function
 * out of native code on the board's compiler, which cost the KnivD
 * benchmark a factor of 2.7 (see mm_pr_se in mmb_runtime.c). */
void mm_pr_se (const char *s);
void mm_pr_ie (MMINTEGER v);
void mm_pr_fe (MMFLOAT v);
void mm_pr_tabe(void);
void mm_pr_tab(void);               /* the ',' separator = a tab       */
int  mm_col   (void);               /* current console column, 0 based */
char *mm_tab(MMINTEGER col);        /* TAB() - returns padding spaces  */

/* ---- number -> string (the interpreter's own algorithms) ----------- */
#define MM_AUTO_PRECISION  999   /* work out the precision automatically */
#define MM_FLOAT_PRECISION 998
#define MM_SIG_DIGITS      9     /* significant digits for PRINT         */
#define MM_FLOAT_DIGITS    6

void mm_int_to_str    (char *p, long long int nbr, int base);
void mm_int_to_str_pad(char *p, long long int nbr, signed char padch,
                       int maxch, int radix);
void mm_float_to_str  (char *p, MMFLOAT f, int m, int n, unsigned char ch);

/* ---- numeric helpers ----------------------------------------------- */
MMINTEGER mm_toint(MMFLOAT v);      /* round to nearest, as MMBasic    */
MMINTEGER mm_idiv (MMINTEGER a, MMINTEGER b);   /*  \   */
MMINTEGER mm_mod  (MMINTEGER a, MMINTEGER b);   /* MOD  */
MMFLOAT   mm_fdiv (MMFLOAT a, MMFLOAT b);       /*  /   */
MMFLOAT   mm_pow  (MMFLOAT a, MMFLOAT b);       /*  ^   */
/* the firmware's domain checks, not the C library's silent nan */
MMFLOAT   mm_sqr  (MMFLOAT v);
MMFLOAT   mm_log  (MMFLOAT v);
MMFLOAT   mm_asin (MMFLOAT v);
MMFLOAT   mm_acos (MMFLOAT v);
MMFLOAT   mm_atan3(MMFLOAT y, MMFLOAT x);       /* MATH(ATAN3 y, x)      */
MMFLOAT   mm_rnd  (void);
void      mm_randomize(MMINTEGER seed);
MMINTEGER mm_sgn  (MMFLOAT v);
MMFLOAT   mm_int  (MMFLOAT v);      /* floor  (MS compatible INT)      */
MMFLOAT   mm_fix  (MMFLOAT v);      /* truncate toward zero            */

/* ---- string functions ---------------------------------------------- */
MMINTEGER mm_asc   (const char *s);
MMINTEGER mm_instr (MMINTEGER start, const char *s, const char *pat);
MMFLOAT   mm_val   (const char *s);
char *mm_chr   (MMINTEGER c);
char *mm_left  (const char *s, MMINTEGER n);
char *mm_right (const char *s, MMINTEGER n);
char *mm_mid   (const char *s, MMINTEGER start, MMINTEGER n); /* n<0 = rest */
char *mm_ucase (const char *s);
char *mm_lcase (const char *s);
char *mm_ltrim (const char *s);
char *mm_rtrim (const char *s);
char *mm_space (MMINTEGER n);
char *mm_strrep(MMINTEGER n, MMINTEGER c);          /* STRING$(n, c)   */
char *mm_str_f (MMFLOAT v,   MMINTEGER m, MMINTEGER n, const char *pad);
char *mm_str_i (MMINTEGER v, MMINTEGER m, MMINTEGER n, const char *pad);
char *mm_hex   (MMINTEGER v, MMINTEGER width);
char *mm_oct   (MMINTEGER v, MMINTEGER width);
char *mm_bin   (MMINTEGER v, MMINTEGER width);

/* BYTE(), TRIM$() and FIELD$() are in mmb_misc.h */
char *mm_format(MMFLOAT val, const char *fmt);

/* ---- date and time: in mmb_datetime.h, compiled into the program --- */

/* ---- BIN2STR$ / STR2BIN --------------------------------------------- */
#define MM_B_INT64  0
#define MM_B_UINT64 1
#define MM_B_INT32  2
#define MM_B_UINT32 3
#define MM_B_INT16  4
#define MM_B_UINT16 5
#define MM_B_INT8   6
#define MM_B_UINT8  7
#define MM_B_SINGLE 8
#define MM_B_DOUBLE 9
/* the converters themselves are in mmb_misc.h */

/* ---- files ----------------------------------------------------------
 * Channels 1..MM_MAXFILES map onto stdio FILE*.  Channel 0 is the
 * console (stdin / stdout), exactly as #0 is in MMBasic.            */
#ifndef MM_MAXFILES
#define MM_MAXFILES 10
#endif

#define MM_F_INPUT  1
#define MM_F_OUTPUT 2
#define MM_F_APPEND 3
#define MM_F_RANDOM 4

void mm_open (const char *fname, int mode, MMINTEGER fnbr);
void mm_close(MMINTEGER fnbr);
/* FLUSH #n - fflush and then fsync, so it survives the power going
 * off.  Channel 0 is the console and does nothing.  Note that Fuzix's
 * fsync syncs the WHOLE filesystem. */
void mm_flush(MMINTEGER fnbr);
void mm_close_all(void);

/* PRINT, with fnbr 0 meaning the console */
void mm_fpr_s (MMINTEGER fnbr, const char *s);
void mm_fpr_i (MMINTEGER fnbr, MMINTEGER v);
void mm_fpr_f (MMINTEGER fnbr, MMFLOAT v);
void mm_fpr_nl(MMINTEGER fnbr);
void mm_fpr_tab(MMINTEGER fnbr);

MMINTEGER mm_eof(MMINTEGER fnbr);
MMINTEGER mm_loc(MMINTEGER fnbr);   /* 1 based read/write position     */
MMINTEGER mm_lof(MMINTEGER fnbr);   /* length in bytes                 */
void      mm_seek(MMINTEGER fnbr, MMINTEGER pos);   /* 1 based         */

char *mm_getline(MMINTEGER fnbr);        /* LINE INPUT -> temp string  */
char *mm_input_str(MMINTEGER nbr, MMINTEGER fnbr);  /* INPUT$()        */
void  mm_input_line(MMINTEGER fnbr);     /* load the INPUT line buffer */
char *mm_input_next(void);               /* next comma separated field */
MMINTEGER mm_atoi(const char *s);
MMFLOAT   mm_atof(const char *s);

/* file management */
void mm_kill  (const char *fname);
void mm_rename(const char *from, const char *to);
void mm_copy  (const char *from, const char *to);
void mm_mkdir (const char *path);
void mm_rmdir (const char *path);
void mm_chdir (const char *path);
char *mm_cwd  (void);
char *mm_dir  (const char *spec, int type, int restart); /* DIR$()      */
void mm_files (const char *spec);                        /* FILES       */
#define MM_DIR_FILE 0
#define MM_DIR_DIR  1
#define MM_DIR_ALL  2

/* ---- DATA / READ / RESTORE ------------------------------------------
 * Every DATA item is compiled into this table.  MMBasic stores the raw
 * text and converts when READ, so each entry carries both forms.     */
#define MM_D_INT 0
#define MM_D_STR 1
#define MM_D_FLT 2
typedef struct {
    int         kind;       /* MM_D_INT, MM_D_STR or MM_D_FLT         */
    MMFLOAT     f;
    MMINTEGER   i;
    const char *s;          /* the source text, MMBasic length prefixed */
} MMDataItem;

/* The table walkers live in mmb_data.h, compiled into the program
 * whose tables they walk; only the MMDataItem type and the MM_D_*
 * kinds stay here, shared with hand-written driver code. */

/* ---- SORT: in mmb_sort.h, compiled into the program that sorts ---- */

/* An array handed to a SUB comes with its bounds: { rank, ub1, ub2, ... }
 * so the callee can index any rank and ask BOUND() about it.          */
int mm_arr_count(const MMINTEGER *bounds);

/* An array whose bounds are worked out while the program runs is a flat
 * pointer plus a bounds table - the same shape an array PARAMETER
 * already has, so indexing, BOUND() and whole-array operations need no
 * new code.  MM_MAXDIM is MMBasic's own (configuration.h). */
#define MM_MAXDIM 5

/* The rest of the array family - DIM a(n)/REDIM's arithmetic, ARRAY
 * SET/ADD/SCALE/SLICE/INSERT and the MATH() reductions - lives in
 * mmb_array.h, compiled into the program that uses it. */

/* ---- misc Tier A ---------------------------------------------------- */
void mm_pause   (MMFLOAT ms);
void mm_error_s (const char *mmstr);     /* the ERROR statement        */

/* ---- running another program -----------------------------------------
 * Collect an argv, then run it and wait.  A non-zero exit is a BASIC
 * error, as a failed MMBasic command would be.  This is what lets a
 * BASIC command hand real work to a separate binary - SAVE IMAGE and
 * LOAD IMAGE are the first - without bcrun or the calling program
 * carrying the code for it. */
void mm_run_begin(void);
void mm_run_arg  (const char *mmstr);
void mm_run_arg_i(MMINTEGER v);
void mm_run_arg_f(MMFLOAT v);
MMINTEGER mm_run_exec(void);
/* CPU RESTART: re-execute argv[0] - process-level restart, which is
 * what the statement means on a machine where the CPU is shared. */
void mm_restart(void);
/* Start it and do NOT wait - PLAY MP3, where the music has to carry on
 * while the BASIC program does.  Returns the pid. */
MMINTEGER mm_run_bg(void);
/* PLAY MP3 and PLAY STOP.  start is mm_run_bg plus the rule that there
 * is only one sound output: it refuses when something is already
 * playing, as MMBasic's PLAY does.  stop signals whatever the KERNEL
 * says is playing - which need not be a player this program started -
 * and returns when the sound output is free again. */
MMINTEGER mm_play_start(void);
/* Who owns the PCM stream (pid, 0 none): the kernel's answer, asked
 * fresh each time - PLAY STOP's discovery, and now the player
 * daemons' too (mmb_play.h). */
MMINTEGER mm_play_owner(void);
/* one control record to the player daemon (mmb_playctl.h); -1 when no
 * daemon is listening */
/* PLAY SOUND/TONE/VOLUME into the kernel synthesiser: 0 done, -2 the
 * output is held by an MP3/MOD player, -1 no such ioctl (fall back to
 * the daemon).  mm_snd_stop silences and releases it. */
MMINTEGER mm_snd_cmd(MMINTEGER op, MMINTEGER a, MMINTEGER b,
                     MMINTEGER p1, MMINTEGER p2, MMINTEGER p3);
MMINTEGER mm_snd_stop(void);
MMINTEGER mm_play_send(MMINTEGER op, MMINTEGER a, MMINTEGER b,
                       MMINTEGER p1, MMINTEGER p2, MMINTEGER p3);
MMINTEGER mm_play_stop(void);
void mm_timer_set(MMFLOAT ms);           /* TIMER = n, milliseconds    */

/* ---- LONGSTRING ------------------------------------------------------
 * The firmware's convention (see misc/Custom.c): a long string lives in
 * an INTEGER array with the byte count in element 0 and the raw payload,
 * NOT NUL terminated, from element 1 onward.  So DIM b%(n) holds up to
 * n*8 bytes.  Every entry point here takes the array base and the total
 * element count, and refuses to run past the end - the manual calls an
 * overflow "undefined", so a clean error is a strict improvement.
 * ------------------------------------------------------------------- */
/* The computation lives in mmb_lstring.h, compiled into the program
 * that uses it.  These two stay: a file channel is bcrun's own stdio
 * stream, which only bcrun can hand to fputc and fread. */
void mm_ls_print  (MMINTEGER fnbr, const MMINTEGER *a, int nl);
MMINTEGER  mm_ls_input  (MMINTEGER *a, int cells, MMINTEGER fnbr, MMINTEGER n);

/* GOSUB/RETURN and the BIT()=/BYTE()=/FLAG family are in mmb_misc.h;
 * the stack depth is MMBasic's 50 levels. */
#ifndef MM_MAXGOSUB
#define MM_MAXGOSUB 50
#endif

/* MID$(s, start, num) = repl$   (the statement form) */
void mm_mid_assign(char *dst, MMINTEGER start, MMINTEGER num, const char *repl);

/* ---- graphics (PC3) --------------------------------------------------
 * Colours are ALWAYS RGB888, as everywhere in MMBasic; the kernel
 * primitive converts to whatever the current mode uses (0/1 for the
 * 1bpp modes, nearest of the 16 logical colours for 4bpp).  Nothing
 * here knows about the mode.
 *
 * On the host these are no-ops returning black, so a translated
 * program that draws still runs under the gates.  */

/* Passed as the colour by a statement that was given none: draw in
 * whatever COLOUR last set.  Resolved inside the primitive so the hot
 * path stays one call, rather than the caller fetching it first. */
#define MM_CUR (-1)

/* MODE n: 1 = 640x480 one bit, 2 = 320x240 sixteen colours.  The
 * PicoMite VGA numbering, which is also the first two HDMI modes - NOT
 * the kernel's own, where 0-5 are the BBC modes and the 320x240 screen
 * is 7.  The mapping is in mm_mode. */
void mm_mode(MMINTEGER n);
/* COLOUR fg [, bg].  Pass MM_CUR as bg to leave the background alone.
 * The kernel holds one colour and knows nothing of a background; bg is
 * kept here for TEXT and filled shapes. */
void mm_colour(MMINTEGER fg, MMINTEGER bg);
MMINTEGER mm_fg(void);
MMINTEGER mm_bg(void);
/* CLS [colour].  Floods whatever is being drawn on - the screen, or the
 * off-screen buffer if one is selected - and puts the text cursor back
 * at the origin.  MM_CUR is a bare CLS: use the background COLOUR set. */
void mm_cls(MMINTEGER rgb);

/* MAP - the sixteen colours the screen can show, as opposed to COLOUR,
 * which picks among them.
 *
 * MODE 2 stores a colour NUMBER per pixel, and MAP says what colour
 * each number is.  So changing entry 8 recolours everything already
 * drawn in colour 8, without touching a pixel - which is what makes
 * fades, flashes and colour cycling cost nothing.
 *
 * mm_map collects; nothing changes until mm_map_set moves the whole
 * palette across during blanking.  MMBasic splits it exactly so
 * (remap332 -> map16quads on SET) because applying a new palette entry
 * by entry shows the picture half recoloured.
 *
 * The colour a program NAMES is unaffected: which entry an RGB888 maps
 * to is fixed bit extraction (MMBasic's RGB121), not a search for the
 * nearest entry, so a remapped palette never moves where new drawing
 * lands. */
void mm_map(MMINTEGER index, MMINTEGER rgb);
void mm_map_set(void);
void mm_map_reset(void);

/* MAP() and COLOUR MAP - the fixed default-palette arithmetic - are in
 * mmb_misc.h; MAP the statement (the live palette) stays below. */
void mm_pixel(MMINTEGER x, MMINTEGER y, MMINTEGER rgb);
MMINTEGER mm_pixel_get(MMINTEGER x, MMINTEGER y);

/* Raw framebuffer bytes out of the current draw target - MMBasic's
 * ReadBufferFast, where mm_pixel_get is its ReadBuffer.  NATIVE format:
 * 4bpp high nibble = left pixel, 1bpp MSB = left, the same layout
 * GFXIOC_BLIT writes.  0 on success, -1 if there is no display or the
 * range is refused.  For code that must LOOK at many pixels: one
 * crossing for a whole row against 2.5us per pixel one at a time. */
MMINTEGER mm_fb_read(MMINTEGER offset, MMINTEGER len, void *buf);
/* The write half of the same window: native bytes into the current draw
 * target (GFXIOC_BLIT).  Same contract, same -1 on no display.  The
 * bytes are native - no colour reduction - so the packing rules are the
 * caller's, and mmb_blit.h is the caller. */
MMINTEGER mm_fb_put(MMINTEGER offset, MMINTEGER len, const void *buf);
/* The same two, a RECTANGLE at a time: `rows` spans of `len` bytes,
 * `stride` apart in the target and contiguous in buf.  One crossing
 * instead of one per row - which is what every rectangle in mmb_blit.h
 * and mmb_sprite.h was paying, twice over for a write (it
 * read-modify-writes).  Same native layout, same -1 on no display. */
MMINTEGER mm_fb_readr(MMINTEGER offset, MMINTEGER len, MMINTEGER rows,
                      MMINTEGER stride, void *buf);
MMINTEGER mm_fb_putr(MMINTEGER offset, MMINTEGER len, MMINTEGER rows,
                     MMINTEGER stride, const void *buf);
/* Both-axis scroll with wrap (GFXIOC_SCROLL2): dx > 0 picture right,
 * dy > 0 picture up; fill is RGB888, or -1 leave, -2 wrap.  -1 on no
 * display. */
MMINTEGER mm_fb_scroll2(MMINTEGER dx, MMINTEGER dy, MMINTEGER fill);

/* Which native index an RGB888 colour becomes, since the palette and
 * the nearest-match are the kernel's.  -1 if there is no display.
 * Sets the drawing colour as a side effect, which costs nothing: every
 * drawing call pushes its own colour first. */
MMINTEGER mm_colour_index(MMINTEGER rgb);

/* What raw framebuffer bytes mean: (stride << 8) | bpp, -1 for no
 * display.  One call rather than two because neither changes without a
 * mode change and both are small. */
MMINTEGER mm_fb_geom(void);
/* A line.  Axis-aligned ones become a single span in the kernel, which
 * is an order of magnitude cheaper than plotting them point by point. */
void mm_line(MMINTEGER x1, MMINTEGER y1, MMINTEGER x2, MMINTEGER y2,
             MMINTEGER rgb);
/* MM.HRES / MM.VRES - the drawable size, straight from the kernel, so
 * it follows a mode change without the program knowing anything. */
MMINTEGER mm_hres(void);
MMINTEGER mm_vres(void);
/* The two batched primitives everything in mmb_gfx.h is built from: a
 * run of points (two shorts each) and a run of rectangles (four), both
 * drawn in one colour.  The array is passed to the kernel as it stands
 * - that layout is what the batch ioctls already read - so a circle
 * crosses into the kernel a handful of times, not once per pixel. */
void mm_plot(const short *xy, MMINTEGER n, MMINTEGER rgb);
void mm_fill(const short *xyxy, MMINTEGER n, MMINTEGER rgb);
/* MMBasic's PIXEL x%(), y%(), c%().  Either the float or the integer
 * pointer of each pair is used, whichever the array actually is.  With
 * both colour pointers NULL the whole run is drawn in rgb, and MM_CUR
 * there means whatever COLOUR last set - MMBasic's scalar-colour and
 * no-colour cases. */
void mm_pixels(const MMFLOAT *xf, const MMINTEGER *xi,
               const MMFLOAT *yf, const MMINTEGER *yi,
               const MMFLOAT *cf, const MMINTEGER *ci,
               MMINTEGER rgb, MMINTEGER count);

/* PRINT @(x, y [, mode]) - MMBasic's fun_at.  Puts the text cursor at a
 * PIXEL position and returns "", so it composes inside PRINT:
 *
 *     PRINT @(0, 0) Str$(Timer - t)
 *
 * In a graphics mode PRINT draws glyphs through whatever is being drawn
 * on, so text follows the drawing into the framebuffer instead of going
 * to the console - which draws on the screen and scrolls it.  mode is
 * MMBasic's PrintPixelMode: 1 draws over what is there, 2 swaps ink and
 * paper. */
char *mm_at(MMINTEGER x, MMINTEGER y, MMINTEGER mode);

/* The cell of a font, in pixels, straight from the kernel's own table -
 * the same table the console draws from, so a program never carries a
 * copy of a font or a hardwired idea of how big one is.  TEXT needs it
 * because justification is arithmetic on the cell size.
 *
 * Fonts are numbered as MMBasic numbers them, from 1.  Returns the
 * number of characters the font covers, and distinguishes two failures
 * that must not be confused:
 *
 *      0   there is a display, but no font of that number - an error,
 *          as it is in MMBasic
 *     -1   there is no display at all, so the question is meaningless.
 *          The host build, where a translated program must still run
 *          and drawing is silently nothing. */
MMINTEGER mm_fontinfo(MMINTEGER font, MMINTEGER *w, MMINTEGER *h);
/* What FONT last selected.  TEXT's omitted font and scale are these,
 * not 1 and 1 - Draw.c cmd_text takes both from gui_font - and the
 * primitive that lays TEXT out lives in a header, on the far side of
 * this file's statics, so it has to ask. */
void mm_font_cur(MMINTEGER *font, MMINTEGER *scale);
/* OPTION CONSOLE SERIAL | SCREEN | BOTH | NONE - the reference's own
 * bitmask (MM_Misc.c:5178): 1 serial, 2 screen, 3 both, 0 neither.  In
 * a graphics mode this is what decides whether a PRINT reaches the
 * serial line as well as the picture, which is the difference between
 * a trace you can read and one the screen scrolls away. */
void mm_console(MMINTEGER mode);

/* Where font n's glyph data IS - MM.INFO(FONT ADDRESS n).
 *
 * There is no MMU here, so the kernel's answer is an address this
 * program can simply read, and the fonts are const so they sit in XIP
 * flash and never move.  That is what lets a program draw MMBasic's
 * glyphs onto something the kernel has never heard of - an ILI9341 on
 * SPI, say - instead of carrying a second copy of the font.
 *
 * The first four bytes at the address are the font's own header:
 * width, height, first character, count.  The glyph for character c
 * starts at addr + 4 + (c - first) * width * height / 8, packed MSB
 * first with no padding.  MMBasic's layout, unchanged.
 *
 * 0 for a font that does not exist, and 0 where there is no display -
 * unlike mm_fontinfo there is nothing useful to say about the second
 * case, and an address of 0 is unreadable either way. */
MMINTEGER mm_fontaddr(MMINTEGER font);

/* DefineFont n - register a font of THIS PROGRAM'S own, numbers 10-16
 * (1-9 are the built-in nine, shared with the console and every other
 * program, and the translator refuses them).
 *
 * The mirror of mm_fontaddr: nothing is copied, the glyphs stay in the
 * program's image and the kernel reads them where they lie.  `addr'
 * points at the four-byte header documented above and `bytes' spans
 * header and glyphs together; the data must already be in that layout,
 * which is what the translator's byte-swap of a DefineFont block
 * produces.
 *
 * Called from the program's prologue rather than where the block sits,
 * because MMBasic binds fonts when the program is loaded - a block at
 * the bottom of a file is in force at the top of it.  The registration
 * dies with the process; no other program can see it.
 *
 * 0, or -1 where there is no display or the kernel refuses it. */
MMINTEGER mm_fontdef(MMINTEGER font, MMINTEGER addr, MMINTEGER bytes);

/* FONT #n [, scale] - the font PRINT draws in, and how big.  Unlike
 * TEXT's own font argument this one sticks, and it decides where PRINT
 * puts the next line: a 24x32 font fills the screen in seven lines
 * where font 1 takes nineteen. */
void mm_font(MMINTEGER font, MMINTEGER scale);

/* TEXT's glyph run: len characters at a PIXEL position, in a font and
 * size and colours the caller chose rather than the ones COLOUR and
 * FONT last set, and bg < 0 for MMBasic's transparent background.
 *
 * The cursor moves as MMBasic's GUIPrintChar moves CurrentX - to the far
 * end of what was drawn - and CurrentX is the cursor PRINT @ sets, so a
 * PRINT after a TEXT carries on from where the text finished.  Anything
 * PRINT had half-collected belongs to the old position and is drawn
 * before the cursor moves.
 *
 * Where the run BEGINS is all of the work, and none of it is here: see
 * mmg_text in mmb_gfx.h. */
/* orient is one of MMG_ORIENT_* (mmb_gfx_text.h), which is MMBasic's
 * Draw.h numbering: the kernel turns the glyphs and walks the pen the
 * way GUIPrintChar does, because the fonts are the kernel's and their
 * bits never cross to this side. */
void mm_gtext(MMINTEGER x, MMINTEGER y, MMINTEGER font, MMINTEGER scale,
              MMINTEGER fg, MMINTEGER bg, const char *s, MMINTEGER len,
              MMINTEGER orient);

/* FRAMEBUFFER - draw off-screen, then show it in one go.  0 means the
 * screen ("N") and 1 the off-screen buffer ("F"), in every argument
 * below.  MMBasic's LAYER, MERGE and second buffers are not here yet.
 *
 * A mode change discards the buffer, so CREATE belongs after MODE.  It
 * is also given up automatically when the program ends - nothing leaks
 * if it never calls CLOSE. */
/* which: 1 = the F buffer (FRAMEBUFFER CREATE), 2 = the layer
 * (FRAMEBUFFER LAYER).  Created and closed separately, as MMBasic
 * creates and closes them. */
void mm_fb_create(MMINTEGER which);
void mm_fb_close(MMINTEGER which);
void mm_fb_write(MMINTEGER which);
/* Where drawing goes right now (0 N, 1 F, 2 L) - so a primitive that
 * must switch targets can put the program's choice back. */
MMINTEGER mm_fb_cur(void);
/* wait: non-zero for MMBasic's ",B" - start at the top of the frame */
void mm_fb_copy(MMINTEGER src, MMINTEGER dst, MMINTEGER wait);
void mm_fb_wait(void);
/* MERGE: the layer over F onto the screen, skipping the transparent
 * index (0-15).  Neither source is changed. */
void mm_fb_merge(MMINTEGER colour);

/* INKEY$ - the key that has been pressed, or "" if none has.  Does not
 * wait, and leaves the terminal as it found it, so INPUT still works
 * and a program that stops does not take the shell's echo with it. */
char *mm_inkey(void);

/* ---- GPIO ------------------------------------------------------------
 *
 * The one crossing.  SETPIN and PIN themselves are in mmb_gpio.h as
 * static functions, so a program that touches no pins carries none of
 * it; this is here only because the on-board cc has no ioctl.
 *
 * op is one of the three below.  Returns the pin's level for a read, 0
 * for a write or a direction change, and -1 if the kernel refused -
 * which for a pin number it does not have is what SETPIN reports. */
#define MM_GPIO_DIR 0                   /* val: 0 input, 1 output      */
#define MM_GPIO_PUT 1                   /* val: 0 low, 1 high          */
#define MM_GPIO_GET 2
/* Claim a resource from the kernel's pin lock (pinlock.c): val is the
 * class, PLK_PIN or PLK_ADC.  0, or -1 if it is not ours to have.
 *
 * This is the ONLY crossing SETPIN makes now, and it makes it once.
 * The pin traffic itself is register stores in mmb_gpio.h, because an
 * ioctl costs 1.488us on this machine against about ten nanoseconds for
 * the store it would be wrapping.  The claim has to come through here
 * rather than through <sys/pc3io.h>'s own wrapper for the reason this
 * whole function exists: the on-board cc has no ioctl.
 *
 * DIR/PUT/GET above are kept for hand-written C and for the host build;
 * translated programs no longer use them. */
#define MM_GPIO_CLAIM 3
MMINTEGER mm_gpio(MMINTEGER op, MMINTEGER pin, MMINTEGER val);

/* The counting inputs - SETPIN FIN/CIN/PER on GP4-GP7 (kernel:
 * countpin.c; design: PLAN-count.md).  The ONE pin mode that is not a
 * register store: counting needs an interrupt, so the counters live in
 * the kernel and every crossing goes through here.
 *
 * A NEW libcall rather than new ops inside mm_gpio, deliberately: the
 * FIN gate does not fit mm_gpio's byte-packed wire struct, and - the
 * deciding reason - bcrun's skew protection refuses by libcall NAME,
 * so a program using counting on an old bcrun is refused at load
 * instead of misbehaving through mm_gpio's default case.
 *
 * op is one of the six below.  val carries the gate/option/cycles for
 * a configure, the new count for SET, and comes back as the reading
 * for READ (live count on CIN, the last completed gate's latch on
 * FIN/PER - the scaling to Hz or ms is mmb_gpio.h's).  Configure, SET
 * and OFF return 0 or -1 refused; a refused READ returns 0, because
 * -1 is a value a CIN counter can legitimately hold (Pin(n) = -1). */
#define MM_PINCT_FIN  0
#define MM_PINCT_CIN  1
#define MM_PINCT_PER  2
#define MM_PINCT_READ 3
#define MM_PINCT_SET  4
#define MM_PINCT_OFF  5
MMINTEGER mm_pinct(MMINTEGER op, MMINTEGER pin, MMINTEGER val);

/* EDGE CAPTURE, which is how Pulsin( and Distance( are measured here -
 * PLAN-pulsin.md.  A busy-wait cannot do it on this machine: the 5ms
 * tick holds di() for 14-18us about 345 times a second, and a second
 * runnable process takes the measurer off the CPU for HALF A SECOND.
 * The kernel timestamps the edges in the GPIO interrupt instead, so
 * the program may be arbitrarily late and still read an exact width.
 *
 * POLL does the one ioctl and caches the ring, returning the running
 * edge count; US and LVL then read that cache by ring index, so a poll
 * that finds three new edges costs one syscall and six lookups.  Its
 * own libcall NAME for the usual skew reason. */
#define MM_PINCAP_ARM  0
#define MM_PINCAP_OFF  1
#define MM_PINCAP_POLL 2
#define MM_PINCAP_US   3
#define MM_PINCAP_LVL  4
#define MM_CAP_RING    16
MMINTEGER mm_pincap(MMINTEGER op, MMINTEGER pin, MMINTEGER arg);

/* The PIO output word buffer (WS2812/BITSTREAM, mmb_pioout.h): the
 * address of the kernel's PSRAM buffer the DMA reads - the DMA must
 * never read process memory on this machine (the swapper moves it).
 * 0 if unavailable.  Its own libcall NAME for the usual skew reason:
 * a program using the strip commands on an old bcrun is refused at
 * load instead of turning -1 into a pointer. */
MMINTEGER mm_pobuf(void);

/* The ioctls, from the kernel's gpio.h.  Duplicated rather than
 * included, as the graphics numbers are, so the runtime does not need
 * the FUZIX tree on its include path.  Keep them in step. */
#define MM_GPIOC_SET     0x0531
#define MM_GPIOC_SETRW   0x0534
#define MM_GPIOC_GETBYTE 0x0533
/* and the counting block, from the kernel's pico_ioctl.h */
#define MM_GPIOC_CNT_FIN  0x0537
#define MM_GPIOC_CNT_CIN  0x0538
#define MM_GPIOC_CNT_PER  0x0539
#define MM_GPIOC_CNT_READ 0x053A
#define MM_GPIOC_CNT_SET  0x053B
#define MM_GPIOC_CNT_OFF  0x053C
#define MM_GPIOC_PIOOUT_BUF 0x053D
#define MM_GPIOC_CNT_CAP   0x053E
#define MM_GPIOC_CNT_CAPRD 0x053F
/* pinlock, from the kernel's pico_ioctl.h - on /dev/sys, not /dev/gpio */
#define MM_PLKIOC_CLAIM  0x0026
/* and the classes it names.  PLK_PIN and PLK_ADC are all SETPIN needs;
 * <sys/pc3io.h> has the rest. */
#define MM_PLK_PIN       0
#define MM_PLK_PWM       3
#define MM_PLK_ADC       4
/* the PIO output machinery (mmb_pioout.h): the reserved PIO1 state
 * machine and DMA channel, single indices the kernel's pinlock knows */
#define MM_PLK_PIO       5
#define MM_PLK_DMA       6

/* RP2350B.  Not 28: that is the RP2040's count, and it put the PC3's
 * own DS3231 alarm on GP32 out of reach. */
#define MM_GPIO_NPINS 48

/* ---- errors, and ON ERROR SKIP/IGNORE ------------------------------- *
 *
 * mm_error prints and exits - EXCEPT while ON ERROR SKIP/IGNORE is armed,
 * when it records the error and RETURNS.  That is the whole reason for
 * the macros below: a raise site can no longer assume it never comes
 * back, and code written on that assumption would carry on using the very
 * value it just rejected.  Every raise in the runtime therefore leaves
 * its function through MM_RAISE/MM_RAISEV.
 *
 * The state lives in the PROGRAM's memory, bound once at startup, so a
 * guard in generated code is a load and a branch rather than a libcall:
 *   state[0]  poison - "unwinding to the end of this statement"
 *   state[1]  the OptionErrorSkip counter: 0 abort, -1 ignore, n>0 count
 */
void mm_error(const char *msg);
void mm_fatal(const char *msg);     /* never skippable: out of memory  */
void mm_err_bind(int *state);       /* generated code hands us its pair */
/* Save-and-clear / restore the whole error state round an interrupt
 * handler - MMBasic's GotAnInterrupt and cmd_ireturn.  One slot, because
 * interrupts never nest.  Used by mmb_int.h. */
void mm_int_err_push(void);
void mm_int_err_pop(void);
/* Microseconds since start - SETTICK's clock off the board, where
 * mmb_int.h reads TIMER0 itself. */
MMINTEGER mm_us(void);
MMINTEGER mm_rand32(void);          /* the hardware RNG; 0 if unavailable */
/* ON KEY: the next decoded key without consuming it (0 = none), and the
 * consume.  A key the poll peeks and does not want stays queued for
 * INKEY$, which is what makes the any-key form's "the key is still
 * there" and the specific form's "the key is eaten" both true. */
MMINTEGER mm_key_peek(void);
void mm_key_drop(void);
/*
 * The next few take int, not MMINTEGER, and that is not a style
 * choice.  Under bcrun every entry point here is reached through a
 * wrapper that pulls arguments off the VM stack by SLOT, and the slots
 * are 32 bits: an int parameter is one slot, an MMINTEGER is two.  A
 * wrapper written I(0), I(1), I(2) for three MMINTEGER parameters
 * therefore reads the low half of the first, the HIGH half of the
 * first, and the low half of the second.
 *
 * That is not theoretical.  mm_i2c_open(38, 39, 400) arrived at the
 * kernel as sda=38, scl=0, khz=39, and mm_rtcreg(reg, val, 1) wrote 0
 * to every register it was asked to set - which on the DS3231's control
 * register clears INTCN and turns the alarm pin into a 1 Hz square
 * wave, so the arming test PASSED by producing one edge a second from
 * the wrong mechanism entirely.
 *
 * A pin number, a register, a 7-bit address and a transfer length all
 * fit an int, and every other small-integer entry point here already
 * takes one (mm_restore, mm_gosub_push, mm_putc).  Matching them makes
 * the natural wrapper the correct one, which is worth more than the
 * width.  Nothing on the HOST can catch this class of bug: there the
 * runtime is called directly with real C prototypes.
 */
/* RTC GETREG / RTC SETREG - one DS3231 register.  write 0 reads and
 * returns the value; write 1 writes val and returns it back (a write to
 * the control register comes back with EOSC masked out, because the
 * kernel will not let a program stop the clock).  -1 if there is no RTC.
 * Arming an alarm is writing these registers, which is what MMBasic
 * does too - it has no alarm command either. */
MMINTEGER mm_rtcreg(int reg, int val, int write);
/* I2C2 - the second controller on header pins.  open assigns the pins,
 * starts it, and sets the transfer timeout in milliseconds, which is
 * where MMBasic keeps it too: I2C2 OPEN speed, timeout, and every
 * transfer afterwards uses it.  0 there means "no timeout" on a
 * PicoMite and a long cap here - a non-preemptive kernel cannot wait
 * for ever on one program's behalf.
 *
 * xfer is one whole transaction, read or write.  hold is MMBasic's
 * option bit 0: end without a STOP so the next transfer is a repeated
 * START on the same device, for the devices that require a genuine
 * combined transfer.
 *
 * 0 on success, or a NEGATIVE ERRNO so the caller can say which
 * failure it was - ETIMEDOUT and EIO are different faults and MMBasic
 * distinguishes them too. */
MMINTEGER mm_i2c_open(int sda, int scl, int khz, int timeout_ms);
/* The general form: bus 0 is the fixed one (GP20/21, the QWIIC socket
   and the DS3231), bus 1 is I2C2 on header pins.  Every transfer sets
   MM.I2C and none of them raises - MMBasic's own contract. */
MMINTEGER mm_i2c_msg(int bus, int addr, int read, int n,
                     unsigned char *buf, int hold);
MMINTEGER mm_i2c_stat(void);            /* MM.I2C: 0 ok, 1 none, 2 stop */
MMINTEGER mm_i2c_setstat(MMINTEGER r);
MMINTEGER mm_i2c_xfer(int addr, int read, int n, unsigned char *buf,
                      int hold);
/* SPI0 - MMBasic's SPI, on header pins (SPI1 is the SD card).  open
 * takes the pins ALREADY SORTED into sck/tx/rx: MMBasic works each
 * pin's role out from the pin itself rather than from the order it was
 * written, and mmb_spi.h does that before calling here.  hz, mode
 * (0-3) and bits (4-16) are OPEN's three arguments.
 *
 * xfer moves len UNITS - a unit is 16 bits when bits > 8.  tx alone
 * writes, rx alone reads, both together writes and reads.  It returns
 * the units moved, or a negative errno.  The buffers are used WHERE
 * THEY LIE, so a whole display frame is one call. */
MMINTEGER mm_spi_open(int sck, int tx, int rx, int hz, int mode, int bits);
MMINTEGER mm_spi_xfer(unsigned char *tx, unsigned char *rx, int len);
void mm_spi_close(void);
void mm_i2c_close(void);
void mm_on_error(int mode, MMINTEGER n);   /* 0 abort 1 clear 2 ignore 3 skip */
/* Write or discard the PRINT line held while armed - the statement
 * guard calls it at the end of every statement.  See mm_putc. */
void mm_pr_commit(void);
MMINTEGER mm_errno(void);           /* MM.ERRNO                        */
char *mm_errmsg(void);              /* MM.ERRMSG$                      */

/* The PC3 release, as major.mmpp so the fields compare as one number
 * (0.10 reads higher than 0.09).  BUMP THIS WITH PC3_RELEASE in the
 * kernel's config.h.
 *
 * That instruction was here from the start and was followed exactly
 * once: this said 0.10 for v0.11, v0.12 and v0.13, so every program
 * that asked the machine what it was running got an answer three
 * releases old.  `relcheck.sh` in the platform directory compares this
 * with PC3_RELEASE and the manual's date line, and is in the recipe
 * now - a comment asking to be kept in step is not a mechanism. */
#define MM_RELEASE 0.28
MMFLOAT mm_ver(void);               /* MM.VER                          */
char *mm_device(void);              /* MM.DEVICE$ - "Fuzix"            */
char *mm_cmdline(void);             /* MM.CMDLINE$                     */
void mm_argv_bind(int argc, char **argv);

/* MM.INFO(...) - the sub-keywords this machine can answer.  MMBasic has
 * dozens more, nearly all about hardware or a program store that is not
 * here; these are the ones a program running on a PC3 can use, and the
 * ones the Game*Mite corpus actually asks for.
 *
 * MM.DEVICE$ is the FIRMWARE ("Fuzix") and MM.INFO(PLATFORM) is the
 * BOARD ("PC3"), which is MMBasic's own division of the two.
 */
int   mm_board_no(void);            /* 2 or 3, for PLATFORM            */
char *mm_platform(void);            /* MM.INFO(PLATFORM)               */
char *mm_path(void);                /* MM.INFO(PATH)    dir + '/'      */
char *mm_current(void);             /* MM.INFO(CURRENT) the program    */
char *mm_drive(void);               /* MM.INFO(DRIVE)   always "A:"    */
MMINTEGER mm_exists_file(const char *path); /* 1 file, -1 dir, 0 none  */
MMINTEGER mm_exists_dir(const char *path);
MMINTEGER mm_filesize(const char *path);    /* -1 none, -2 a directory */
MMINTEGER mm_disksize(void);                /* MM.INFO(DISK SIZE); 0 unknown */
MMINTEGER mm_pinno(const char *name);       /* "GP8" -> 8              */
MMINTEGER mm_fontwidth(void);       /* MM.FONTWIDTH,  cell x scale     */
MMINTEGER mm_fontheight(void);      /* MM.FONTHEIGHT, cell x scale     */
MMINTEGER mm_hpos(void);            /* MM.HPOS - the pixel cursor      */
MMINTEGER mm_vpos(void);            /* MM.VPOS                         */

/* KEYDOWN(n): 0 the count of held keys, 1..6 the codes (1 = most
 * recent), 7 the modifier bitmap, 8 the locks.  Drains the console
 * first, as MMBasic does - see the definition. */
MMINTEGER mm_keydown(MMINTEGER n);

/* Run the collected argv and read its output - see mm_run_pipe in
   mmb_runtime.c.  Finish with mm_run_pipe_close, always. */
int mm_run_pipe(void);
MMINTEGER mm_run_pipe_close(int fd);
MMINTEGER mm_run_pipe_read(int fd, void *buf, int n);

#define MM_RAISE(msg)      do { mm_error(msg); return; } while (0)
#define MM_RAISEV(msg, v)  do { mm_error(msg); return (v); } while (0)

/* Somewhere real to write when a raise has already happened and the
 * caller keeps running to the end of its statement. */
char      *mm_ssink(void);          /* a writable empty string         */
MMFLOAT   *mm_fsink(void);
MMINTEGER *mm_isink(void);

void mm_end  (void);                /* the END statement               */
MMFLOAT mm_timer(void);             /* ms since TIMER=, with fraction  */

#ifdef __cplusplus
}
#endif
#endif /* MMB_RUNTIME_H */
