ROOT=../..
FUZIX_ROOT=$(ROOT)
USERCPU=armm0
VERBOSE=1
include $(FUZIX_ROOT)/Target/rules.$(USERCPU)

OBJS = mmbedit.o shim.o editor.o keywords.o

# Recursive descent over a whole file wants more than the 8K default;
# the loader honours PT_GNU_STACK (see PC3-DEVNOTES.md).
mmbedit: LINKER_OPT += --defsym __stack_size=16384

all: mmbedit

mmbedit: $(OBJS)
	$(LINKER) -o mmbedit.debug $(CRT0) $(OBJS) $(LINKER_OPT)
	$(STRIP) -o mmbedit mmbedit.debug

$(OBJS): mmbedit.h
editor.o keywords.o: mmb_compat.h

clean:
	rm -f *.o mmbedit mmbedit.debug
