/* Generated by mmb2c.py v0.1 from /home/peter/src/FUZIX/Applications/CC/hwtest/heaptest.bas */
/*
 * Implied global variables (created by first use, never
 * declared with DIM):
 *     i                    FLOAT    first used line 8     in the main program
 *     j                    FLOAT    first used line 47    in the main program
 */

#include "mmb_runtime.h"
#include <math.h>
#include <string.h>
#include <stdlib.h>

/* ---- constants ---- */

/* ---- global variables ---- */
MMFLOAT v_i;   /* implied, first seen line 8 */
MMFLOAT v_j;   /* implied, first seen line 47 */

/* Arrays and strings: one block, allocated once from the PSRAM heap. */
struct mm_vars {
    MMFLOAT v_a[(4LL) + 1];
    MMFLOAT v_d[(3LL) + 1];
    MMFLOAT v_m[(2LL) + 1][(2LL) + 1];
    MMINTEGER v_n[(4LL) + 1];
    char v_s[MM_STRSZ];
    char v_t[(3LL) + 1][MM_STRSZ];
    char v_u[MM_STRSZ];
};
static struct mm_vars *H;

/* ---- DATA items: parallel primitive arrays, so no
 * struct layout crosses the bcrun VM boundary ---- */
static const int __mmb_data_kind[] = {
    2,
    2,
    2,
    2,
    1,
};
static const MMFLOAT __mmb_data_f[] = {
    1.5,
    2.5,
    3.5,
    4.5,
    0.0,
};
static const MMINTEGER __mmb_data_i[] = {
    0LL,
    0LL,
    0LL,
    0LL,
    0LL,
};
static const char *__mmb_data_s[] = {
    "\003" "1.5",
    "\003" "2.5",
    "\003" "3.5",
    "\003" "4.5",
    "\012" "datastring",
};

/* ---- forward declarations ---- */

/* ---- subroutines and functions ---- */

/* ---- main program ---- */
int main(void)
{
    unsigned __mark = mm_mark(); (void)__mark;
    H = mm_heap(sizeof *H);   /* arrays and strings */
    mm_data_init4(__mmb_data_kind, __mmb_data_f, __mmb_data_i, __mmb_data_s, 5);
    mm_pr_s("\016" "stage 1: alive");
    mm_pr_nl();
    mm_pr_s("\035" "stage 2: float array declared");
    mm_pr_nl();
    {
        MMFLOAT __lim1 = (MMFLOAT)(4LL);
        for (v_i = (MMFLOAT)(0LL); v_i <= __lim1; v_i += 1) {
            H->v_a[(int)(mm_toint(v_i))] = ((v_i) * (1.5));
        }
    }
    mm_pr_s("\034" "stage 3: float array written");
    mm_pr_nl();
    mm_pr_s("\007" "  a(0)=");
    mm_pr_f(H->v_a[(int)(0LL)]);
    mm_pr_s("\006" " a(4)=");
    mm_pr_f(H->v_a[(int)(4LL)]);
    mm_pr_nl();
    {
        MMFLOAT __lim2 = (MMFLOAT)(4LL);
        for (v_i = (MMFLOAT)(0LL); v_i <= __lim2; v_i += 1) {
            H->v_n[(int)(mm_toint(v_i))] = mm_toint(((v_i) * ((MMFLOAT)(7LL))));
        }
    }
    mm_pr_s("\026" "stage 4: integer array");
    mm_pr_i(H->v_n[(int)(0LL)]);
    mm_pr_i(H->v_n[(int)(4LL)]);
    mm_pr_nl();
    mm_sset(H->v_s, "\005" "hello");
    mm_pr_s("\030" "stage 5: scalar string [");
    mm_pr_s(H->v_s);
    mm_pr_s("\001" "]");
    mm_pr_nl();
    mm_release(__mark);
    mm_sset(H->v_s, mm_scat(H->v_s, "\006" " world"));
    mm_pr_s("\021" "stage 6: concat [");
    mm_pr_s(H->v_s);
    mm_pr_s("\001" "]");
    mm_pr_nl();
    mm_release(__mark);
    mm_pr_s("\014" "stage 7: len");
    mm_pr_i((MMINTEGER)mm_slen(H->v_s));
    mm_pr_s("\006" " mid [");
    mm_pr_s(mm_mid(H->v_s, 2LL, 3LL));
    mm_pr_s("\001" "]");
    mm_pr_nl();
    {
        MMFLOAT __lim3 = (MMFLOAT)(3LL);
        for (v_i = (MMFLOAT)(0LL); v_i <= __lim3; v_i += 1) {
            mm_release(__mark);
            mm_sset(H->v_t[(int)(mm_toint(v_i))], mm_scat("\001" "e", mm_str_f(v_i, 0, MM_AUTO_PRECISION, "\001" " ")));
        }
    }
    mm_pr_s("\027" "stage 8: string array [");
    mm_pr_s(H->v_t[(int)(0LL)]);
    mm_pr_s("\002" "][");
    mm_pr_s(H->v_t[(int)(3LL)]);
    mm_pr_s("\001" "]");
    mm_pr_nl();
    {
        MMFLOAT __lim4 = (MMFLOAT)(3LL);
        for (v_i = (MMFLOAT)(0LL); v_i <= __lim4; v_i += 1) {
            H->v_d[(int)(mm_toint(v_i))] = mm_read_f();
        }
    }
    mm_pr_s("\023" "stage 9: READ float");
    mm_pr_f(H->v_d[(int)(0LL)]);
    mm_pr_f(H->v_d[(int)(3LL)]);
    mm_pr_nl();
    mm_release(__mark);
    mm_sset(H->v_u, mm_read_s());
    mm_pr_s("\027" "stage 10: READ string [");
    mm_pr_s(H->v_u);
    mm_pr_s("\001" "]");
    mm_pr_nl();
    {
        MMFLOAT __lim5 = (MMFLOAT)(2LL);
        for (v_i = (MMFLOAT)(0LL); v_i <= __lim5; v_i += 1) {
            {
                MMFLOAT __lim6 = (MMFLOAT)(2LL);
                for (v_j = (MMFLOAT)(0LL); v_j <= __lim6; v_j += 1) {
                    H->v_m[(int)(mm_toint(v_i))][(int)(mm_toint(v_j))] = ((((v_i) * ((MMFLOAT)(10LL)))) + (v_j));
                }
            }
        }
    }
    mm_pr_s("\022" "stage 11: 2d array");
    mm_pr_f(H->v_m[(int)(0LL)][(int)(0LL)]);
    mm_pr_f(H->v_m[(int)(2LL)][(int)(2LL)]);
    mm_pr_nl();
    mm_pr_s("\022" "stage 12: all done");
    mm_pr_nl();
    return 0;
}
