ROOT = ../..
include $(ROOT)/Target/rules.armm0
CFLAGS += -DNETD_LITTLE_ENDIAN
# ping's round-trip time: the Pico Computer 3 has a microsecond timer
# reachable with three loads and no syscall (sys/pc3io.h).  Without it
# ping falls back to gettimeofday, whose tv_usec Fuzix leaves at zero.
CFLAGS += -DPC3_US_CLOCK

SRCS  = netd.c slip.c uip.c uiplib.c timer.c clock-arch.c uip_arp.c telnet.c
SRCS += echoping.c dig.c gethostbyname.c httpd.c coconic.c ping.c ntpdate.c
SRCS += htget.c tinyirc.c linein.c ifconfig.c tftpd.c

OBJS = $(SRCS:.c=.o)

APPS = netd-slip telnet echoping dig httpd ping ntpdate htget tinyirc ifconfig
APPS += tftpd

all: $(APPS)

netd-slip: $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o slip.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

telnet: $(CRT0) telnet.o gethostbyname.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

echoping: $(CRT0) echoping.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

dig: $(CRT0) dig.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

httpd: $(CRT0) httpd.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

ping: $(CRT0) ping.o gethostbyname.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

ntpdate: $(CRT0) ntpdate.o gethostbyname.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

htget:	$(CRT0) htget.o gethostbyname.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

tinyirc: $(CRT0) tinyirc.o linein.o gethostbyname.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

tftpd: $(CRT0) tftpd.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif

ifconfig: $(CRT0) ifconfig.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
ifdef ELF2FUZIX
	$(STRIP) -o $@.bin $(STRIP_OPT) $@.debug
	$(ELF2FUZIX) -o $@ $@.bin
else
	$(STRIP) -o $@ $(STRIP_OPT) $@.debug
endif


size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.data *.text *.debug size.report *~

rmbak:
	rm -f *~ core
